### ISSUE TITLE
Incorrect completion suggestions in Intergrated Terminal

### ISSUE THREAD

**Issue by lc9er** [coc-extensions/coc-powershell#110] opened 2020-09-10 15:03 UTC
I stumbled across this almost right away, after the most recent update, but haven't had a chance to submit a report, until now. 

### System Details

* _Vim or NeoVim?_:
NeoVim
* _Version of Vim (run `vim --version`) or NeoVim_ (run `nvim --version`):
0.4.4
* _Version of `coc-powershell` (in Vim or NeoVim: `:CocList extensions coc-powershell`)_:
0.1.3
* _Operating System_:
Win10 - 1909
* _PowerShell version (in PowerShell: `$PSVersionTable`)_:
7.0.3

### Issue Description

I am experiencing a problem with...

When using the Integrated Console, if I enter a remote PSSession and try to use completion with any command (like `cd` or `ls`, etc), I only get suggestions from the local directory - not the remote one that I'm currently in.

#### Expected Behaviour

-- Description of what *should* be happening --

I should receive completion suggestions for the current remote session. 

#### Actual Behaviour

-- Description of what actually happens --

I'm getting only suggestions from the last local directory I was in, before entering the remote PS Session.

**Comment by corbob** [comment] 2020-09-11 02:12
🤔 I don't currently have access to systems to remote into and test this with, could you try the same scenario in `pwsh` directly? As well, if you have vscode installed in the PowerShell Integrated Terminal there? This would tell us if the issue is with pwsh, or PowerShell Editor Services.

**Comment by lc9er** [comment] 2020-09-12 00:35
Great call on this. I wasn't having any problems with `pwsh`.  I installed the latest VSCode (I don't actually use it anymore) and the Powershell extension and was able to reproduce the bug, so I'll open an issue with the PS Editor Services project. Thanks for your help!

**Comment by TylerLeonhardt** [comment] 2020-09-12 01:50
Let's go ahead and close this here since we have an issue in PSES

**Closed** 2020-09-12 01:50 UTC
