### ISSUE TITLE
Autoformat command

### ISSUE THREAD

**Issue by yar05** [coc-extensions/coc-powershell#36] opened 2019-07-04 09:14 UTC
Is it possible to use this to autoformat powershell code ?

**Comment by TylerLeonhardt** [comment] 2019-07-05 02:17
In theory this should already work since PowerShell Editor Services (the language server for PowerShell) already supports formatting.

Just need to figure out how to invoke formatting with coc

**Comment by TylerLeonhardt** [comment] 2019-07-05 02:20
Looking at my logs, it looks like the formatting isn’t turned on…

```
"documentFormattingProvider": false,
"documentRangeFormattingProvider": false,
"documentOnTypeFormattingProvider": null,
```

**Comment by yar05** [comment] 2019-07-05 10:40
Is there any way to support you guys with some coins with these efforts? 
IMO this project is going to be very popular as there is nothing else that would provide autoformat and autocomplete for powershell for vim it's a big deal for open-source community that wants to actually start using powershell, Microsoft should make this a priority project ;)

**Comment by TylerLeonhardt** [comment] 2019-07-05 16:04
Right now we're just 2 Microsoft folks (and 1 non-Microsoft folk) moonlighting this project 😅

My team, the PowerShell team, would be the best place to officially own it... but the team (of 13 for all of PowerShell + Win32-OpenSSH) has a lot on its plate at the moment.

Best support would be time, if I'm brutally honest. Helping with docs, reproducing issues so we can fix them, and yes PRs always welcome 😊

We also need to setup a test suite so we don't break things.

If these are something you can help with, we'd be happy for the support 😊

**Comment by yar05** [comment] 2019-07-05 20:50
Is code formatting handles by [AnalysisService.cs](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Analysis/AnalysisService.cs#L315)?

**Comment by JayDoubleu** [comment] 2019-07-05 20:51
Is code formatting handles by [AnalysisService.cs](https://github.com/PowerShell/PowerShellEditorServices/blob/master/src/PowerShellEditorServices/Analysis/AnalysisService.cs#L315)?

**Comment by TylerLeonhardt** [comment] 2019-07-07 06:44
Nice!

The good news is that PowerShell Editor Services already supports handling formatting so if we wanna enable this in coc-powershell, all we have to do is tell coc.nvim that it's supported.

**Comment by yatli** [comment] 2019-08-05 19:22
@TylerLeonhardt I'm trying to implement format handlers for `coc-fsharp` these days, got some hands-on experience with coc.nvim;

Basically:

1. The `formatexpr` option is tied to `gq`, but not `=`. `=` uses built-in indent function, backed by the vimL associated with the file type (indent.vim) -- so that can also be rerouted.
2. Manually call `CocAction('format')` works great -- so is `CocAction('formatSelection', 'v')` -- mind the "mode string" again.
3. Haven't figure out how is the format-while-typing handler called by `coc.nvim` -- may be called during an automatic hard wrap (see 1.)

**Comment by TylerLeonhardt** [comment] 2019-08-05 19:44
I discovered that PSES has poorly hooked up formatting... that relies on this code in the client side:

https://github.com/PowerShell/vscode-powershell/blob/master/src/features/DocumentFormatter.ts

I'm doing some major refactoring of PSES and this code wont be required in the future but for now it is

**Comment by yatli** [comment] 2019-09-16 15:32
@TylerLeonhardt ringring ;)

**Comment by TylerLeonhardt** [comment] 2019-09-17 06:26
Good news and bad news:

bad news - coc.nvim doesn't support:
`vscode.languages.registerDocumentFormattingEditProvider`
`vscode.languages.registerDocumentRangeFormattingEditProvider`
`vscode.languages.registerOnTypeFormattingEditProvider`

so I can't implement this at the moment. That said, PowerShell Editor Services is moving to handle the formatting registration automatically so in the 2.0 version of PowerShell Editor Services formatting should work out of the box.

**Comment by yatli** [comment] 2019-09-17 06:30
good to know!

**Comment by TylerLeonhardt** [comment] 2019-09-17 06:30
We will race with coc.nvim to see what happens first: https://github.com/neoclide/coc.nvim/issues/1179

**Comment by yatli** [comment] 2019-09-17 06:32
race conditions! :D

yeah for F#, I just declared these capabilities in the language server so it works automatically.
Let's see how `coc.nvim` will respond.

**Comment by TylerLeonhardt** [comment] 2019-09-17 06:34
> I just declared these capabilities in the language server

Right. PowerShell Editor Services never did this for some reason... really not sure why.

**Comment by TylerLeonhardt** [comment] 2020-08-31 03:10
Thanks to PSES 2.0, this works now :) `:call CocAction('format')`

**Closed by TylerLeonhardt** 2020-08-31 03:10 UTC
Labels: enhancement
